[package]
name = "postkeeper"
version = "0.1.0"
authors = ["Enhance Ltd <backend@enhance.com>"]
edition = "2018"
default-run = "postkeeper"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
